### ISSUE TITLE
Consider relicensing to a GPL-compatible license.

### ISSUE THREAD

**Issue by teo-tsirpanis** [juergenpf/Collections#2]
The project is currently licensed under the MIT License with an advertisement clause. That clause makes the license incompatible with the GNU General Public License.

To boost adoption and ease the issues of using a custom license, I recommend you to switch Collections' license to the original MIT license, without any custom clauses. You can do it without a problem since you wrote the entire library and I of course consent to have my pending changes in #1 relicensed.

**Comment by juergenpf** [comment]
Done. Thx for the heads up.
